name: linter
on: 
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
    paths-ignore:
      - README.md
      - LICENSE
jobs:
  linter:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]
    steps:
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Linter
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.51.2
          args: --timeout 3m
