name: tests
on: 
  push:
    branches:
      - 'main'
      - 'feature/*'
      - 'fix/*'
    paths-ignore:
      - README.md
      - LICENSE

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go-version: [ '1.19' ]

    steps:
      - name: Setup
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go-version }}

      - name: Checkout
        uses: actions/checkout@v3

      - name: Dependencies
        run: go mod download

      - name: Tests
        run:  go test -race ./...
